### ISSUE TITLE
BetterDiscord Plugin

### ISSUE THREAD

**Issue by SpicyTakis** [SynapseTech/TimezoneDB#53]
The [BetterDiscord] plugin for TimezoneDB

To Do:
- [ ] Add a Powercord plugin under `platforms/betterdiscord`
- [ ] Display locations
  - [ ] Message
  - [ ] User hover cards
  - [ ] Autocomplete
- [ ] Cache timezone data

[BetterDiscord]: https://betterdiscord.app/

**Comment by LizAinslie** [comment]
Lol dupe of #54
